Script started on 2017年03月28日 (週二) 21時09分47秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop $[00m whoami;pwd
pd2vm
/home/pd2vm/Desktop
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop $[00m git confih=[K[Kg -l
user.email=sherisea870125@gmail.com
user.name=sherisea
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.lab1.url=git@github.com:sherisea/lab1.git
remote.lab1.fetch=+refs/heads/*:refs/remotes/lab1/*
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop $[00m git config -l[3Pwhoami;pwdgit push lab1remote add lab1 git@github.com:sherisea/laab1.git[A[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop $[00m [C[C[C[Cpush[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cremote add[4Pcommit[1Padd .mv lab1.script lab1[4Pcat lab1.script[3@scrip[C[C[C[C[C[C[C[C[C[C[C[C[Cgit clone https://github.com/sherisea/lab1.gitt[A[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop $[00m cd Desktop[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cgit clone https://github.com/sherisea/lab1.gitt[A[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop $[00m cd Desktop[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cgit clone https://github.com/sherisea/lab1.gitt
fatal: destination path 'lab1' already exists and is not an empty directory.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop $[00m 
Script done on 2017年03月28日 (週二) 21時10分26秒
