Script started on 2017年03月28日 (週二) 14時19分44秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop/lab1 $[00m git add .lab1.scriptmv lab1.script lab1[4Pcat lab1.script[3@scrip[C[C[C[C[C[C[C[C[C[C[C[C[Cgit clone https://github.com/sherisea/labb1.git[A[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop/lab1 $[00m [C[C[C[C[Config -l[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1Pwhoami; pwdsgit add lab1.script[7Pwhoami; pwds
pd2vm
No command 'pwds' found, did you mean:
 Command 'pads' from package 'pads' (universe)
 Command 'pwdx' from package 'procps' (main)
 Command 'pods' from package 'pmtools' (universe)
 Command 'pwd' from package 'coreutils' (main)
pwds: command not found
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop/lab1 $[00m whoami; pwds[3Pgit add .lab1.scriptmv lab1.script lab1[4Pcat lab1.script[3@scrip[C[C[C[C[C[C[C[C[C[C[C[C[Cgit clone https://github.com/sherisea/labb1.git[A[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop/lab1 $[00m [C[C[C[C[Config -l[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
user.email=sherisea870125@gmail.com
user.name=sherisea
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop/lab1 $[00m git config -l[1Pwhoami; pwds[3Pgit add .lab1.scriptmv lab1.script lab1[4Pcat lab1.script[3@scrip[C[C[C[C[C[C[C[C[C[C[C[C[Cgit clone https://github.com/sherisea/labb1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop/lab1 $[00m exit

Script done on 2017年03月28日 (週二) 14時20分11秒
